"""empty message

Revision ID: 2b9abae62a88
Revises: 74f6b2238a38
Create Date: 2024-08-22 18:03:25.909078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9abae62a88'
down_revision = '74f6b2238a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircargo_status_history', sa.Column('current_carrier', sa.String(length=100), nullable=True))
    op.add_column('cargo_status_history', sa.Column('current_carrier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_status_history', 'current_carrier')
    op.drop_column('aircargo_status_history', 'current_carrier')
    # ### end Alembic commands ###
