"""empty message

Revision ID: 74f6b2238a38
Revises: 
Create Date: 2024-08-21 13:46:33.487526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f6b2238a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_location', sa.String(length=100), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=False),
    sa.Column('current_carrier', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('contents_description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('insurance', sa.String(length=100), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('sender_contact', sa.String(length=50), nullable=True),
    sa.Column('receiver_name', sa.String(length=100), nullable=True),
    sa.Column('receiver_contact', sa.String(length=50), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('airway_bill_number', sa.String(length=20), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_location', sa.String(length=100), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=False),
    sa.Column('current_carrier', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('contents_description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('insurance', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_address', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('contents_description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=855), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('aircargo_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircargo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircargo_id'], ['aircargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircargo_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircargo_id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircargo_id'], ['aircargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=255), nullable=True),
    sa.Column('cargos', sa.Integer(), nullable=False),
    sa.Column('aircargo', sa.Integer(), nullable=False),
    sa.Column('parcel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aircargo'], ['aircargo.id'], ),
    sa.ForeignKeyConstraint(['cargos'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['parcel'], ['parcel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcel_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcel_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_pic', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('telephone_phone', sa.String(length=16), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('user_attribute', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('address_two', sa.String(length=300), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('staffs')
    op.drop_table('roles_users')
    op.drop_table('parcel_update')
    op.drop_table('parcel_status_history')
    op.drop_table('insurance')
    op.drop_table('carrier')
    op.drop_table('cargo_update')
    op.drop_table('cargo_status_history')
    op.drop_table('aircargo_update')
    op.drop_table('aircargo_status_history')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('parcel')
    op.drop_table('cargo')
    op.drop_table('aircargo')
    # ### end Alembic commands ###
